# .config/starship.toml // config file for the starship prompt

add_newline = false

[character]
# success_symbol = "[â¯](bold purple)"
# error_symbol = "[â¯](bold red)"
success_symbol = "[>](bold purple)"
error_symbol = "[>](bold red)"
